PROMPTS = [
    "Studio product photo of a ceramic coffee mug, isolated on white background, soft shadows",
    "Vintage leather backpack on a neutral backdrop, high detail product photography",
    "Wooden dining chair, centered composition, clean studio lighting",
    "Modern desk lamp, isolated object, sharp focus",
    "Potted succulent plant in a simple clay pot, studio photo",
    "Mountain bicycle side view, product catalog style",
    "Acoustic guitar standing upright, white seamless background",
    "Running shoe product shot, realistic materials",
    "Compact camera, centered on neutral background",
    "Glass perfume bottle with metallic cap, studio lighting",
    "Mechanical keyboard, top-down product photograph",
    "Wireless headphones, isolated object render",
    "Travel suitcase, product photography, clean background",
    "Desk fan, realistic industrial design photo",
    "Electric kettle, catalog-style image",
    "Table clock, centered and isolated",
    "Wooden stool, studio photograph",
    "Sports water bottle, realistic product shot",
    "Classic teapot, clean lighting",
    "Office stapler, isolated on white",
    "Toy robot figurine, front three-quarter view",
    "Chess knight piece, studio macro photo",
    "Ceramic vase with simple geometry",
    "Lantern with metal frame, isolated",
    "Treasure chest prop, realistic materials",
    "Sci-fi helmet, product render style",
    "Medieval shield, centered object photo",
    "Decorative mask, neutral background",
    "Pocket watch, high-detail macro",
    "Snow globe, isolated product image",
    "Red apple, studio fruit photography",
    "Banana bunch, isolated on white",
    "Pumpkin, detailed texture, neutral background",
    "Pineapple, centered product shot",
    "Loaf of rustic bread, studio lighting",
    "Layered cake, isolated dessert photo",
    "Hamburger, commercial food photography",
    "Croissant, high-resolution bakery photo",
    "Cheese wheel, product-style image",
    "Coffee beans in a small pile, studio macro",
    "Oak tree sapling, isolated botanical photograph",
    "Cactus plant, centered composition",
    "Bonsai tree on plain backdrop",
    "Sunflower bloom, studio botanical image",
    "Fern plant, isolated on white",
    "Mushroom cluster, detailed nature photo",
    "Seashell collection, product photography",
    "Coral fragment, isolated object image",
    "Smooth river stone, macro photo",
    "Crystal geode specimen, studio shot",
    "Golden retriever dog standing, full body, neutral background",
    "Domestic cat sitting, isolated animal portrait",
    "Horse standing profile view, clean background",
    "Rabbit full body studio photograph",
    "Parrot perched on a branch, isolated",
    "Turtle side view, high detail",
    "Frog on neutral surface, macro wildlife style",
    "Owl standing front-facing, isolated",
    "Fox full body portrait, clean backdrop",
    "Penguin standing, centered composition",
    "Sports car three-quarter view, studio background",
    "Motorcycle side profile, product photo",
    "Pickup truck isolated on white",
    "Scooter product photograph",
    "Sailboat model, studio shot",
    "Helicopter scale model, isolated",
    "Steam locomotive model, clean background",
    "Space shuttle model, centered composition",
    "Submarine model, product photography",
    "Construction excavator, catalog image",
    "Modern sofa, furniture catalog photograph",
    "Bookshelf unit, isolated furniture shot",
    "Round coffee table, studio lighting",
    "Bed frame, product catalog style",
    "Armchair, centered composition",
    "Wardrobe cabinet, isolated object photo",
    "Floor mirror, realistic studio image",
    "Office desk, clean product photograph",
    "Nightstand, isolated furniture render",
    "Bean bag chair, catalog image",
    "Castle tower miniature, tabletop photography",
    "Windmill model, isolated on white",
    "Lighthouse miniature, detailed product shot",
    "Pagoda model, studio photo",
    "Stone bridge miniature, centered composition",
    "Fantasy cottage model, product-style image",
    "Ancient column ruin prop, isolated",
    "Fountain sculpture, studio lighting",
    "Clock tower miniature, neutral background",
    "Greenhouse model, product photograph",
    "Electric drill, isolated hardware product photo",
    "Adjustable wrench, studio macro image",
    "Hammer, centered object photograph",
    "Hand saw, isolated on white",
    "Tape measure, product catalog shot",
    "Toolbox, realistic studio image",
    "Paint roller, isolated object",
    "Garden shovel, product photography",
    "Clamp tool, clean background",
    "Flashlight, high-detail product image",
    "Retro television set, isolated studio photo",
    "Game controller, product photography",
    "Desktop computer tower, centered composition",
    "Computer mouse, clean catalog image",
    "Tablet device, isolated object shot",
    "Smartphone standing upright, studio photo",
    "VR headset, realistic product photography",
    "Portable speaker, neutral backdrop",
    "Microphone, isolated studio image",
    "External hard drive, product shot",
    "Dragon statuette, fantasy collectible, studio lighting",
    "Knight figurine, tabletop collectible photo",
    "Alien creature toy, isolated product image",
    "Spaceship miniature, clean background",
    "Magic wand prop, centered composition",
    "Crystal ball on stand, product photography",
    "Pirate ship model, detailed studio shot",
    "Ancient artifact replica, isolated",
    "Mythical phoenix sculpture, neutral background",
    "Golem figurine, high-detail collectible photo",
    # Object + limbs
    "Party hat with arms and legs, studio product photography",
    "Coffee mug with tiny human legs",
    "Desk lamp with octopus tentacles instead of a stand",
    "Banana with robotic spider legs",
    "Watering can with bird wings",
    "Teapot with crab legs",
    "Backpack with four elephant legs",
    "Chess rook with muscular human arms",
    "Fire hydrant with insect legs",
    "Traffic cone with tiny sneakers",
    # Hybrid household objects
    "Toaster shaped like a medieval castle",
    "Chair shaped like a whale",
    "Grand piano shaped like a crocodile",
    "Vacuum cleaner shaped like a snail",
    "Washing machine shaped like a pumpkin",
    "Lantern shaped like a jellyfish",
    "Backpack shaped like a beetle",
    "Teapot shaped like an owl",
    "Clock shaped like a pineapple",
    "Coffee maker shaped like a dragon",
    # Food-object hybrids
    "Hamburger with mechanical gears visible inside",
    "Croissant shaped like a dragon",
    "Pumpkin with cathedral architecture carved into it",
    "Apple growing brass clockwork mechanisms",
    "Pretzel made of polished chrome",
    "Cake shaped like a volcano",
    "Pineapple made from stacked books",
    "Banana covered in ceramic tiles",
    "Cheeseburger woven from wicker",
    "Loaf of bread made of crystal",
    # Biological oddities
    "Cactus growing computer keyboards instead of spines",
    "Tree whose branches are antlers",
    "Mushroom with stained glass cap",
    "Fern made entirely of feathers",
    "Sunflower with clock faces instead of petals",
    "Rose bush made of metal chains",
    "Bonsai tree growing tiny houses",
    "Palm tree with umbrella leaves",
    "Oak sapling with crystal bark",
    "Coral made from pencils",
    # Mechanical organisms
    "Mechanical owl built from brass instruments",
    "Robot rabbit made from teacups",
    "Dragonfly made from fountain pens",
    "Turtle assembled from luggage pieces",
    "Fox made from folded cardboard",
    "Octopus built from desk lamps",
    "Mechanical peacock with fan blades for feathers",
    "Crab made from pocket watches",
    "Horse made from wicker furniture",
    "Beetle assembled from kitchen utensils",
    # Weird accessories
    "Top hat with dozens of tiny doors",
    "Sneaker covered in bird nests",
    "Umbrella growing mushrooms",
    "Helmet with miniature windmills attached",
    "Crown made from antlers and keys",
    "Backpack covered in clocks",
    "Pair of boots with bird wings",
    "Bowler hat with coral growth",
    "Glove made from stained glass",
    "Scarf woven from electrical cables",
    # Architectural creatures
    "Walking cathedral with four elephant legs",
    "Lighthouse with crab legs",
    "Castle tower with bird wings",
    "Pagoda shaped like a turtle",
    "Greenhouse growing on the back of a tortoise",
    "Windmill shaped like an owl",
    "Clock tower with octopus tentacles",
    "Bridge curled up like a sleeping cat",
    "Library shaped like a hedgehog",
    "Water tower with insect legs",
    # Toy-like surrealism
    "Rubber duck wearing knight armor",
    "Action figure of a refrigerator",
    "Toy train shaped like a dragon",
    "Teddy bear made of stone",
    "Wind-up penguin with tank treads",
    "Toy robot disguised as a birthday cake",
    "Stuffed giraffe made of denim",
    "Building block castle growing vines",
    "Snow globe containing another snow globe",
    "Jack-in-the-box shaped like a lighthouse",
    # Geometry oddities
    "Cube covered in feathers",
    "Sphere made from hundreds of keys",
    "Torus made of braided bread",
    "Pyramid built from coffee mugs",
    "Dodecahedron made from books",
    "Mobius strip woven from rope",
    "Icosahedron made of tree roots",
    "Knot sculpture made from sausages",
    "Cube assembled from bird cages",
    "Sphere woven from antlers",
    # Things that should not exist
    "Skeleton of a goldfish displayed like a dinosaur fossil",
    "Party hat evolved into a crab-like creature",
    "Vacuum cleaner with antlers",
    "Fire extinguisher growing flowers",
    "Mailbox with bird wings",
    "Traffic cone wearing medieval armor",
    "Accordion shaped like a crocodile",
    "Teacup balanced on six insect legs",
    "Screwdriver with peacock feathers",
    "Garden gnome transformed into a lighthouse",
    # Trellis nightmare fuel
    "Bird nest woven from metal chains",
    "Romanesco broccoli made of glass",
    "Coral reef shaped like a bicycle",
    "Chainmail pumpkin",
    "Peacock made of tree roots",
    "Gyroid sculpture covered in fur",
    "Lace umbrella with octopus tentacles",
    "Wicker dragon skeleton",
    "Crystal bird nest filled with keys",
    "Ball of tangled clocks and antlers",
]
